development:
  adapter: postgresql
  encoding: unicode
  database: rails_testing_talk_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: rails_testing_talk_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: rails_testing_talk_production
  pool: 5
  username:
  password:
